# vim: nofoldenable: list:
# PIVARD Julien
# Dernière modification : Samedi 11 novembre[11] 2017

###############
# Partie Fixe #
###############

COMPILATEUR	= gprbuild
OPTCOMPILATEUR	= -d -p
CC		= $(COMPILATEUR) $(OPTCOMPILATEUR)

RM		= rm
OPTRM		= -vrf

GPR		= build.gpr

GPR_MODE	= -Xmode=$(MODE)
GPR_VERBEUX	= -Xverb=$(VERBEUX)
GPR_STRICT	= -Xstri=$(STRICT)
OPTGPR		= $(GPR_MODE) $(GPR_VERBEUX) $(GPR_STRICT)

SORTIEDOC	= --output=$(FORMAT)
OPTDOCUMENT	= -w -l $(SORTIEDOC)

CIBLECOMPILE	= compileprojet
EXECUTABLE	= ./bin/$(MODE)/executable

#############################################
# Les modifications sont à faire en dessous #
#############################################

# Permet de choisir le format de la documentation
# -w Affiche des warnings pour tout toutes les docs oublié.
# -l Cherche avant les déclarations plutôt que après.
# -p Ajoute les private dans la documentation.
FORMAT		= html

# Fixer le nom de l'application
NOMAPP		= DES

# Pour activer le mode debug mettre à true
# ACTIVER_DEBUG = [true|false]
ACTIVER_DEBUG	= true

# Pour activer le mode verbeux
# ACTIVER_VERB = [true|false]
ACTIVER_VERB	= false

# Pour activer le mode strict
# ACTIVER_STRICT = [true|false]
ACTIVER_STRICT	= true

# Fixer les arguments qui seront donné en entré de l'application
# lors de l'exécution
ARGUMENTSAPPLI	=
