# vim: nofoldenable: list:
# PIVARD Julien
# Dernière modification : Jeudi 04 octobre[10] 2018

# Options possible pour la compilation de la documentation.
# -w Affiche des warnings pour tout toutes les docs oublié.
# -l Cherche avant les déclarations plutôt que après.
# -p Ajoute les private dans la documentation.

###############
# Partie Fixe #
###############

COMPILATEUR	= gprbuild
OPTCOMPILATEUR	= -d -p
CC		= $(COMPILATEUR) $(OPTCOMPILATEUR)

RM		= rm
OPTRM		= -vrf

GPR		= build.gpr

GPR_MODE	= -Xmode=$(MODE)
GPR_VERBEUX	= -Xverb=$(VERBEUX)
GPR_STRICT	= -Xstri=$(STRICT)
GPR_W_SONT_E	= -Xwarn_sont_err=$(WARN_DEVIENNENT_ERREURS)
OPTGPR		= $(GPR_MODE) $(GPR_VERBEUX) $(GPR_STRICT) $(GPR_W_SONT_E)

SORTIEDOC	= --output=$(FORMAT)
OPTDOCUMENT	= -w --enable-build $(SORTIEDOC)

OPTCOMPTAGE	= -l #-w

CIBLECOMPILE	= compileprojet
EXECUTABLE_SEQ	= ./bin/$(MODE)/executable_sequentiel
EXECUTABLE_TAC	= ./bin/$(MODE)/executable_taches
EXECUTABLE_RAV	= ./bin/$(MODE)/executable_ravenscar

EXTENSION_CHIFFRE_S	= sequ.chiffre
EXTENSION_CHIFFRE_T	= task.chiffre
EXTENSION_CHIFFRE_R	= rave.chiffre
EXTENSION_DECHIFFRE_S	= $(EXTENSION_CHIFFRE_S).sequ.dechiffre
EXTENSION_DECHIFFRE_T	= $(EXTENSION_CHIFFRE_T).task.dechiffre
EXTENSION_DECHIFFRE_R	= $(EXTENSION_CHIFFRE_R).rave.dechiffre

EXECUTABLE	= $(EXECUTABLE_SEQ)

#############################################
# Les modifications sont à faire en dessous #
#############################################

# Permet de choisir le format de la documentation
FORMAT		= html

# Fixer le nom de l'application
NOMAPP		= DES

# Pour activer le mode debug mettre à true
# ACTIVER_DEBUG = [true|false]
ACTIVER_DEBUG	= true

# Pour activer le mode verbeux
# ACTIVER_VERB = [true|false]
ACTIVER_VERB	= false

# Pour activer le mode strict
# ACTIVER_STRICT = [true|false]
ACTIVER_STRICT	= true

# Pour activer le traitement des avertissements comme si c'était des erreurs
# ACTIVER_WARN_SONT_ERREURS = [true|false]
ACTIVER_WARN_SONT_ERREURS	= false

# -l Montre le chemin complet du fichier désigné
# --show-rule Ajoute le nom de la règle qui à déclenché le signalement
# -o gnatcheck.out Pour désigner un fichier de sortie
OPT_CHECK	= -l -U --show-rule

# Fixer les arguments qui seront donné en entré de l'application
# lors de l'exécution
VARNOMFICHIER	= test.txt
ARGUMENTSAPPLI	= -c $(VARNOMFICHIER) lovecrft
ARGSCHIFFRE	= --chiffrer $(VARNOMFICHIER) lovecrft
ARGSDECHIFFRES	= --dechiffrer $(VARNOMFICHIER).$(EXTENSION_CHIFFRE_S) lovecrft
ARGSDECHIFFRET	= --dechiffrer $(VARNOMFICHIER).$(EXTENSION_CHIFFRE_T) lovecrft
ARGSDECHIFFRER	= --dechiffrer $(VARNOMFICHIER).$(EXTENSION_CHIFFRE_R) lovecrft

# Emplacement des binaires si ils ne sont pas localisable par les makefile
GNAT_BIN_PERSO	=

# Emplacement des sources
DOSSIERSRC	= src
