# vim: nofoldenable: list:
# PIVARD Julien
# Dernière modification : Jeudi 16 juillet[07] 2020

###############
# Partie Fixe #
###############

GPR		= des-unitaire.gpr
OPTGPR		=

NOM_DOSSIER	= tests_unitaire
CHEMIN_OBJET	= ../obj/$(NOM_DOSSIER)
CHEMIN_EXEC	= ../bin/$(NOM_DOSSIER)

EXECUTABLE	= $(CHEMIN_EXEC)/test_unitaire_executable

#############################################
# Les modifications sont à faire en dessous #
#############################################

# Fixer les arguments qui seront donné en entré des tests unitaires
# lors de l'exécution
ARGUMENTSAPPLI	=

# Emplacement des binaires si ils ne sont pas localisable par les makefile
GNAT_BIN_PERSO	=

# Emplacement des sources
DOSSIERSRC	= ../src src_tests_unitaire
